---
- name: Install SSH public key on AWS instances
  hosts: aws_cluster
  become: yes
  tasks:
    - name: Add SSH key to authorized_keys
      ansible.posix.authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', '/Users/rishi/.ssh/aws_key.pub') }}"

